env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions:
    - '.svelte'
plugins:
  - '@typescript-eslint'
  - 'simple-import-sort'
  - 'svelte'
rules:
  {
    'simple-import-sort/exports': 2,
    'simple-import-sort/imports': 2,
    '@typescript-eslint/ban-ts-comment': 0,
    '@typescript-eslint/no-unused-vars': 2,
    'no-console': 'error',
  }
